
project_id = "zygpupmeradizrachnqj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://axzora.com"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.recover-failed-payment]
verify_jwt = true

[functions.wallet-payment]
verify_jwt = true

[functions.sso-auth]
verify_jwt = false

[functions.validate-virtual-card]
verify_jwt = false
